# exceptions/__init__.py

from .MistakeLimitReachedError import MistakeLimitReachedError
